### ISSUE TITLE
There's a new update

### ISSUE THREAD

**Issue by ghost** [dnsev-h/E-Hentai-Downloader#1]
The source updated the script, any chance this will be updated too? =)
Being able to save tags with your additional feature is a godsend.

**Comment by dnsev-h** [comment]
https://github.com/dnsev-h/E-Hentai-Downloader/tree/x1.31.6

**Comment by Asinin3** [comment]
The new update broke this script, the download buttons etc are no-longer showing up on gallery pages for me after it auto updated. @dnsev-h

**Comment by Asinin3** [comment]
Updated manually again and it's fixed now.

**Comment by dnsev-h** [comment]
So it's working for you now?

**Comment by Asinin3** [comment]
Yeah, i don't know what happened before. But the script auto-updated and its functionality just disappeared from the website. I checked again for new updates and nothing was found through violentmonkey. Then a couple days later, after violentmonkey still couldn't see an update i just came back here and manually grabbed the script again and it said it updated and was working fine again.

**Comment by dnsev-h** [comment]
You're right, it looks like I was using the incorrect download URL for the script. I have updated the script to be updated, but the version is the same. All involved in this thread may want to manually reinstall the script this time; all future updates should work automatically.
